### ISSUE TITLE
mongo_connector.errors.InvalidConfiguration

### ISSUE THREAD

**Issue by Ziggoto** [mongodb-labs/elastic2-doc-manager#16]
I was trying to run this command:

`mongo-connector -m 127.0.0.1:7000 -t 127.0.0.1:8884 -d elastic2-doc-manager`

And I got this:

> No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 9, in <module>
    load_entry_point('mongo-connector==2.4.1', 'console_scripts', 'mongo-connector')()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 1059, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 118, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 842, in apply_doc_managers
    DocManager = import_dm_by_name(dm['docManager'])
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 812, in import_dm_by_name
    return import_dm_by_path(full_name)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 829, in import_dm_by_path
    "vailable doc managers." % package)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2-doc-manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers.

I also checked my directory `/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers`:

> -rw-r--r-- 1 root staff  5701 Set 13 11:30 doc_manager_base.py
-rw-r--r-- 1 root staff  5713 Set 13 11:30 doc_manager_base.pyc
-rw-r--r-- 1 root staff  6559 Set 13 11:30 doc_manager_simulator.py
-rw-r--r-- 1 root staff  9741 Set 13 11:30 doc_manager_simulator.pyc
-rw-r--r-- 1 root staff 14089 Set 19 14:01 elastic2_doc_manager.py
-rw-r--r-- 1 root staff 12593 Set 19 14:01 elastic2_doc_manager.pyc
-rw-r--r-- 1 root staff 13281 Set 19 14:46 elastic_doc_manager.py
-rw-r--r-- 1 root staff 11841 Set 19 14:46 elastic_doc_manager.pyc
-rw-r--r-- 1 root staff  5508 Set 13 11:30 formatters.py
-rw-r--r-- 1 root staff  6508 Set 13 11:30 formatters.pyc
-rw-r--r-- 1 root staff    75 Set 19 14:46 __init__.py
-rw-r--r-- 1 root staff   271 Set 19 14:46 __init__.pyc
-rw-r--r-- 1 root staff 11952 Set 13 11:30 mongo_doc_manager.py
-rw-r--r-- 1 root staff 11275 Set 13 11:30 mongo_doc_manager.pyc
-rw-r--r-- 1 root staff 31261 Set 13 11:30 schema.xml
-rw-r--r-- 1 root staff 13761 Set 13 11:30 solr_doc_manager.py
-rw-r--r-- 1 root staff 13844 Set 13 11:30 solr_doc_manager.pyc

When I tried to run in the iPython console I got this:

```python
from mongo_connector import doc_managers 
help(doc_managers)
```
Output:

> Help on package mongo_connector.doc_managers in mongo_connector:
>
> NAME
>
>   mongo_connector.doc_managers
>
> FILE
>    /usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/__init__.py
>
> PACKAGE CONTENTS
>    doc_manager_base
>    doc_manager_simulator
>    elastic2_doc_manager
>    elastic_doc_manager
>    formatters
>    mongo_doc_manager
>    solr_doc_manager

Does anyone know how to help?

**Comment by Ziggoto** [comment]
Sorry, I was writing wrong the name of module. It is with underscore. 

The correct command is:

`mongo-connector -m 127.0.0.1:7000 -t 127.0.0.1:8884 -d elastic2_doc_manager`
