### ISSUE TITLE
"is not a valid ObjectId" exception

### ISSUE THREAD

**Issue by afoninsky** [mongodb-labs/elastic2-doc-manager#31]
I'm trying to sync mongodb with elasticsearch, fails with error:
```
2016-12-10 08:08:24,029 [INFO] elasticsearch:66 - DELETE http://elasticsearch.software.svc.cluster.local:9200/_search/scroll [status:404 request:0.001s]
2016-12-10 08:08:24,030 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 714, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 867, in rollback
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
InvalidId: u'ae.gov.tra.uaevr' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 714, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 867, in rollback
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
InvalidId: u'ae.gov.tra.uaevr' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

2016-12-10 08:08:25,052 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 140117855426304)> unexpectedly stopped! Shutting down
```

elasticsearch v.2.4.1

Dockerfile:
```
FROM ubuntu:16.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y python python-pip && \
    pip install --upgrade pip setuptools && \
    pip install mongo-connector && \
    pip install elastic2-doc-manager
ENTRYPOINT ["mongo-connector"]
```

config.json:
```
{
    "mainAddress": "mongodb://mongo1.software.svc.cluster.local,mongo2.software.svc.cluster.local,mongo3.software.svc.cluster.local/?replicaSet=rs0",
    "continueOnError": true,
    "verbosity": 2,
    "authentication": {
        "adminUsername": "admin",
        "password": "***"
    },
    "logging": {
      "type": "stream"
    },
    "namespaces": {
        "include": [
          "test-staging.market",
          "test-staging.resources",
          "test-production.market",
          "test-production.resources"
        ],
        "mapping": {
          "test-staging.market": "test-fulltext-staging.market",
          "test-staging.resources": "test-fulltext-staging.resources",
          "test-production.market": "test-fulltext.market",
          "test-production.resources": "test-fulltext.resources"
        }
    },
    "docManagers": [{
        "docManager": "elastic2_doc_manager",
        "targetURL": "elasticsearch.software.svc.cluster.local:9200"
    }]
}

```

**Comment by afoninsky** [comment]
https://github.com/mongodb-labs/mongo-connector/issues/443
