### ISSUE TITLE
KeyError '_id' on upsert

### ISSUE THREAD

**Issue by somechild** [mongodb-labs/elastic2-doc-manager#58]
I experienced the same problem as mentioned [here]( https://github.com/mongodb-labs/mongo-connector/issues/409)
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 267, in run
    docman.upsert(doc, ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 300, in upsert
    doc_id = u(doc.pop("_id"))
KeyError: '_id'
```
I added `_id` to the `includeFields` in the configuration and still experienced the same issue.

**Comment by somechild** [comment]
I fixed the issue by modifying line 300 as follows:
(Original)[https://github.com/mongodb-labs/elastic2-doc-manager/blob/683cc482e53a125b6115ff44aba18dd6031b5408/mongo_connector/doc_managers/elastic2_doc_manager.py#L300]
```
        doc_id = u(doc.pop("_id"))
```
New
```
       doc_id = u(doc.pop("_id")) if doc.has_key("_id") else u(doc.get("ui"))
```

I also don't understand why we're using `pop` on the `doc` when it's being re-added (a few lines below)[https://github.com/mongodb-labs/elastic2-doc-manager/blob/683cc482e53a125b6115ff44aba18dd6031b5408/mongo_connector/doc_managers/elastic2_doc_manager.py#L326]
Also, not sure why my document is being transformed to have the `ui` contain the mongo document's `_id` - but this seems to work.
Can someone confirm my approach or let me know if I'm doing this incorrectly?
