### ISSUE TITLE
importlib_metadata.api.PackageNotFoundError: importlib_metadata

### ISSUE THREAD

**Issue by abhijitbashetti** [mongodb-labs/elastic2-doc-manager#67]
Hi, I have installed the mongo-connector and when I run the same , I get the below error.
MongoDB version is : 4.0
Elasticsearch version is : 6.5.3
Please let me know if any more info is required.

```
D:\>mongo-connector -m 127.0.0.1:27017 -t 127.0.0.1:9200 -d elastic2_doc_manager
Traceback (most recent call last):
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\Scripts\mongo-connector-script.py", line 11, in <module>
    load_entry_point('mongo-connector==3.1.1', 'console_scripts', 'mongo-connector')()
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\mongo_connector-3.1.1-py3.7.egg\mongo_connector\connector.py", line 34, in <module>
    from mongo_connector import config, constants, errors, util
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\mongo_connector-3.1.1-py3.7.egg\mongo_connector\config.py", line 20, in <module>
    from mongo_connector.constants import __version__
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\mongo_connector-3.1.1-py3.7.egg\mongo_connector\constants.py", line 16, in <module>
    import importlib_metadata
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata-0.8-py3.7.egg\importlib_metadata\__init__.py", line 17, in <module>
    __version__ = version(__name__)
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata-0.8-py3.7.egg\importlib_metadata\api.py", line 345, in version
    return distribution(package).version
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata-0.8-py3.7.egg\importlib_metadata\api.py", line 310, in distribution
    return Distribution.from_name(package)
  File "C:\Users\abhijitb\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata-0.8-py3.7.egg\importlib_metadata\api.py", line 158, in from_name
    raise PackageNotFoundError(name)
**importlib_metadata.api.PackageNotFoundError: importlib_metadata**
```

**Comment by andreacodeluppi** [comment]
Hello, same issue here with:
Python version 3.6.7
MongoDB version 4.0.7
Elasticsearch version 5.6.12

Tried to uninstall/install pip and mongo-connector without any success.

**Comment by jaraco** [comment]
You can't use `easy_install` to install `importlib_metadata`. Install your package(s) with pip and you should be fine.
